/*
 * OSvariables.h
 *
 *  Created on: 8 de nov. de 2016
 *      Author: DTUser
 */

#ifndef OSVARIABLES_H_
#define OSVARIABLES_H_

typedef enum {ESTADO_PARADA, ESTADO_ARRANCADO, ESTADO_VUELO, ESTADO_EMERGENCIA,
	ESTADO_IDENTIFICACION, ESTADO_CALIBRACION}tpEstado;
typedef enum {CALIBRACION_IMU, CALIBRACION_BRUJULA}tpModoCalibracion;
typedef enum {NO_TELEMETRIA, TELEMETRIA_BASICA, TELEMETRIA_COMPLETA}tpModoTelemetria;
typedef enum {CONTROL_3EJES, CONTROL_EMPUJE, CONTROL_ALTURA, CONTROL_ACRO}tpModoControl;
typedef enum {MODO_IDENTIFICACION, MODO_IDENTIFICACION_VUELO}tpModoIdentificacion;


#endif /* OSVARIABLES_H_ */
